name: multi replay

on:
  workflow_dispatch:

jobs:
  script-test-1:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: python /scripts/replay.py

  script-test-2:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: python /scripts/replay.py

  script-test-3:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: python /scripts/replay.py

  script-test-4:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: python /scripts/replay.py

  script-test-5:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: python /scripts/replay.py

  script-test-6:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: python /scripts/replay.py

  script-test-7:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: python /scripts/replay.py

  script-test-8:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: python /scripts/replay.py

  script-test-9:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: python /scripts/replay.py

  script-test-10:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: python /scripts/replay.py

  script-test-11:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: python /scripts/replay.py

  script-test-12:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: python /scripts/replay.py

  script-test-13:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: python /scripts/replay.py

  script-test-14:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: python /scripts/replay.py

  script-test-15:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: python /scripts/replay.py

  script-test-16:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: python /scripts/replay.py

  script-test-17:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: python /scripts/replay.py

  script-test-18:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: python /scripts/replay.py

  script-test-19:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: python /scripts/replay.py

  script-test-20:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: python /scripts/replay.py
